import os

API_KEY = os.getenv('GOOGLE_API_KEY')
APPLICATION_CREDENTIALS = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
AUDIO_WAVE_FILE = "audio.wav"
SUB_CLIP_OUTPUT_FILE = "output.mp4"
SUB_AUDIO_OUTPUT_FILE = "output.mp3"
